version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/packages/hello-1"
    schedule:
      interval: "daily"
      time: "02:00"
    labels:
      - "Action: no bump"

  - package-ecosystem: "npm"
    directory: "/packages/hello-2"
    schedule:
      interval: "daily"
      time: "02:00"
    labels:
      - "Action: no bump"
