name: Pull request changelog

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changelog:
    name: 'check changelog'
    runs-on: ubuntu-18.04

    steps:
    - name: Check if version label is present
      id: labels
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const versionLabels = [
            'no-release',
            'patch',
            'minor',
            'major',
          ];

          const { data: pullLabels } = await github.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            per_page: 100,
          });

          const labels = pullLabels.map(label => label.name);

          const versionLabelsPresent = labels
            .filter(name => versionLabels.includes(name));

          console.log(`::debug ::${versionLabelsPresent.length} matching labels`);

          if (versionLabelsPresent.length !== 1) {
            throw new Error('Should have one and only one of no-release, patch, minor, major labels');
          }

          const versionLabel = versionLabelsPresent[0];
          console.log(`::set-output name=version-label::${versionLabel}`)

          const packageLabels = labels.filter(name => name.includes('packages/'));

          if (versionLabel === 'no-release') {
            return;
          }

          if (packageLabels.length !== 1) {
            throw new Error('Pull request should have one package label');
          }

          console.log(`::set-output name=package::${packageLabels[0]}`)

    - name: Fail if no changelog change when needed
      if: steps.labels.outputs.version-label != 'no-release'
      uses: actions/github-script@0.4.0
      env:
        PACKAGE: ${{ steps.labels.outputs.package }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: files } = await github.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            per_page: 100,
          });

          const changelogFile = `${process.env.PACKAGE}/CHANGELOG.md`;

          const fileNotDeletedNames = files
            .filter(file => file.status === 'added' || file.status === 'modified')
            .map(file => file.filename);

          if (!fileNotDeletedNames.includes(changelogFile)) {
            throw new Error('Package CHANGELOG.md Unreleased section shoud have line additions when PR is not a no-release')
          }
